### ISSUE TITLE
[3.0.1] Not working with paginate() method

### ISSUE THREAD

**Issue by Kladislav** [Laragear/CacheQuery#18] opened 2022-11-23 15:48 UTC
### PHP & Platform

8.0.25, Ubuntu 20.04

### Database

PostgreSQL 13

### Laravel version

9.37

### Have you done this?

- [X] I have checked my logs and I'm sure is a bug in this package.
- [X] I can reproduce this bug in isolation (vanilla Laravel install)
- [ ] I can suggest a workaround as a Pull Request

### Expectation

The cache scope should also works with paginate()

### Description

The paginte() method returns TypeError, but if I change it to  simplePaginate method all working fine.

### Reproduction

```php
$model = Example::query()->cache()->paginate();
```

### Stack trace & logs

```shell
{
 "class": "TypeError",
  "message": "Illuminate\\Database\\Query\\Builder::__construct(): Argument #1 ($connection) must be of type Illuminate\\Database\\ConnectionInterface, Laragear\\CacheQuery\\CacheAwareConnectionProxy given, called in /home/mp/htdocs/backend/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php on line 3482"
}
```

**Comment by DarkGhostHunter** [comment] 2022-11-29 17:00
Cannot reproduce. By all means, if it's a bug, then [this test wouldn't pass](https://github.com/Laragear/CacheQuery/blob/68890234fc2de7ce11180ca4d341134a9dd4278c/tests/CacheAwareConnectionProxyTest.php#L234-L241).

**Comment by glarbdev** [comment] 2023-05-20 12:02
I was able to easily replicate this by adding a groupBy clause to the query.

Example:
`$model = Example::query()->groupBy('name')->cache()->paginate();`

It produces the same error and there is no test coverage for the use case.

Edit:
After a little initial diggin it looks like the packages CacheAwareConnectionProxy::select isn't being called when groupBy is called with paginate().  However simplePaginate, & cursorPaginate seem to work fine.

Edit 2:
I did a little further digging and it seems that this line in the Illuminate\Database\Eloquent\Builder::paginate() call is where it fails.

`$total = func_num_args() === 5 ? value(func_get_arg(4)) : $this->toBase()->getCountForPagination();`
spicifically toBase()

**Comment by DarkGhostHunter** [comment] 2023-05-21 05:18
When `getCountForPagination()` calls `runPaginationCountQuery()`, it calls `newQuery()`, which uses late-state binding to create a new connection instance:

```php
/**
 * Get a new instance of the query builder.
 *
 * @return \Illuminate\Database\Query\Builder
 */
public function newQuery()
{
    return new static($this->connection, $this->grammar, $this->processor);
}
```

So the constructor of the Query Builder receives the proxy, which is not a `ConnectionInterface` implementation, hence the error.

Because of this, I had to _extend_ the proxy with the vanilla `Connection` class.

This is fixed on 3.1.1

**Closed as completed** 2023-05-21 05:17 UTC
Labels: bug

**Comment by DarkGhostHunter** [comment] 2023-05-21 05:35
Fixed in v3.1.1

https://github.com/Laragear/CacheQuery/releases/tag/v3.1.1

**Comment by glarbdev** [comment] 2023-05-21 05:40
I just sat down to submit a PR doing the exact same thing but you beat me to it!  
Thanks for your hard work and a wonderful package!

**Comment by DarkGhostHunter** [comment] 2023-05-21 07:55
You welcome. You can tip me whatever you want tho. Happy Sunday. Italo Baeza C.El 21-05-2023, a la(s) 01:40, sscodex ***@***.***> escribió:﻿
I just sat down to submit a PR doing the exact same thing but you beat me to it!
Thanks for your hard work and a wonderful package!
